---
channels:
  - bioconda
  - psi4
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aioeasywebdav=2.4.0=py37h89c1867_1001
  - aiohttp=3.7.4.post0=py37h5e8e339_0
  - alabaster=0.7.12=py_0
  - ambit=0.5.1=hbda204a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - ase=3.22.0=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcrypt=3.2.0=py37h5e8e339_1
  - biopython=1.79=py37h5e8e339_0
  - black=21.9b0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - boost=1.74.0=py37h6dcda5c_3
  - boost-cpp=1.74.0=h312852a_4
  - boto3=1.19.7=pyhd8ed1ab_0
  - botocore=1.22.7=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h5e8e339_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py37h89c1867_0
  - cffi=1.14.6=py37h036bc23_1
  - chardet=4.0.0=py37h89c1867_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - chemfiles=0.10.1=ha770c72_0
  - chemfiles-lib=0.10.1=h28ed3cb_1
  - chemfiles-python=0.10.1=py37h085eea5_1
  - chemps2=1.8.9=hbda204a_2
  - click=8.0.3=py37h89c1867_0
  - coincbc=2.10.5=hcee13e7_1
  - configargparse=1.5.3=pyhd8ed1ab_0
  - coverage=6.1=py37h5e8e339_0
  - cryptography=35.0.0=py37hf1a17b8_1
  - curl=7.79.1=h2574ce0_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.24=py37hcd2ae1e_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datrie=0.8.2=py37h5e8e339_2
  - decorator=5.1.0=pyhd8ed1ab_0
  - dftd3=3.2.1=h84218bc_2
  - dkh=1.2=h173d85e_2
  - docutils=0.17.1=py37h89c1867_0
  - dropbox=11.22.0=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - fftw=3.3.10=nompi_h74d3f13_101
  - filechunkio=1.8=py_2
  - filelock=3.3.2=pyhd8ed1ab_0
  - flask=2.0.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - ftputil=5.0.1=pyhd8ed1ab_0
  - gau2grid=2.0.7=hd18ef5c_0
  - gcp=2.0.2=he991be0_2
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gdma=2.2.6=h0e1e685_6
  - gettext=0.19.8.1=h73d1719_1008
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - google-api-core=1.31.2=pyhd8ed1ab_1
  - google-api-python-client=2.28.0=pyhd8ed1ab_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.7.2=pyh6c4a22f_0
  - google-cloud-storage=1.19.0=py_0
  - google-crc32c=1.1.2=py37hab72019_0
  - google-resumable-media=2.1.0=pyh6c4a22f_0
  - googleapis-common-protos=1.53.0=py37h89c1867_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.49.1=h85b4f2f_0
  - greenlet=1.1.2=py37hcd2ae1e_0
  - grpcio=1.41.1=py37hb27c1af_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - h5py=3.2.1=nompi_py37ha3df211_100
  - harfbuzz=3.0.0=h83ec7ef_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - httplib2=0.20.1=pyhd8ed1ab_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.1=pyhd3deb0d_0
  - imagemagick=7.1.0_13=pl5321hb118871_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=4.8.1=py37h89c1867_0
  - importlib_metadata=4.8.1=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipython=7.28.0=py37h6531663_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=2.0.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=3.0.2=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37h89c1867_0
  - kiwisolver=1.3.2=py37h2527ec5_0
  - krb5=1.19.2=hcc1bbae_2
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.79.1=h2574ce0_1
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgd=2.3.3=h6ad9fb6_0
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.0=h174f98d_1
  - libiconv=1.16=h516909a_0
  - libint2=2.6.0=hc9558a2_9
  - liblapack=3.9.0=8_mkl
  - libnetcdf=4.8.1=nompi_hcd642e3_100
  - libnghttp2=1.43.0=h812cca2_1
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.19.1=h780b84a_0
  - librsvg=2.52.3=hc3c00ef_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.1=h3452ae3_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxc=5.1.5=h84b9e52_1
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py37h5e8e339_0
  - matplotlib-base=3.4.3=py37h1058ff1_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py37he8ac12f_0
  - more-itertools=8.10.0=pyhd8ed1ab_0
  - multidict=5.2.0=py37h5e8e339_0
  - mypy=0.910=py37h5e8e339_0
  - mypy_extensions=0.4.3=py37h89c1867_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.6.3=pyhd8ed1ab_1
  - numpy=1.21.3=py37h31617e3_0
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openbabel=3.1.1=py37h6aa62a1_2
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.2=pyhd8ed1ab_1
  - pandas=1.3.4=py37he8f5f7f_0
  - pango=1.48.10=h54213e6_2
  - paramiko=2.8.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcmsolver=1.2.1.1=py37h6d17ec8_2
  - pcre=8.45=h9c3ff4c_0
  - peppy=0.31.1=pyhd8ed1ab_0
  - periodictable=1.5.2=py_0
  - perl=5.32.1=1_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py37h0f21c89_0
  - pint=0.17=pyhd8ed1ab_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py37h89c1867_1
  - ply=3.11=py_1
  - prettytable=2.2.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.21=pyha770c72_0
  - protobuf=3.19.1=py37hcd2ae1e_0
  - psi4=1.4.1+cd00f19=py37h9fd7210_0
  - psutil=5.8.0=py37h5e8e339_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.5.1=py37h89c1867_0
  - py=1.10.0=pyhd3deb0d_0
  - py-cpuinfo=8.0.0=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycairo=1.20.1=py37hfff247e_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py37h5e8e339_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py37h0b1d2a2_0
  - pynacl=1.4.0=py37h5e8e339_2
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd8ed1ab_1
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37h89c1867_3
  - pytest=6.2.5=py37h89c1867_0
  - pytest-cov=3.0.0=pyhd8ed1ab_0
  - python=3.7.12=hb7a2778_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py37h5e8e339_0
  - qcelemental=0.23.0=pyhd8ed1ab_0
  - qcengine=0.20.0=pyhd8ed1ab_0
  - ratelimiter=1.2.0=py_1002
  - rdkit=2021.09.2=py37h13c2175_0
  - readline=8.1=h46c0cb4_0
  - regex=2021.10.23=py37h5e8e339_0
  - reportlab=3.5.68=py37h69800bb_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rsa=4.7.2=pyh44b312d_0
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - setuptools=58.3.0=py37h89c1867_0
  - simint=0.7=h642920c_1
  - simplejson=3.17.5=py37h5e8e339_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.2.1=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=6.3.0=hdfd78af_0
  - snakemake-minimal=6.3.0=pyhdfd78af_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sphinx=4.2.0=pyh6c4a22f_0
  - sphinx_rtd_theme=1.0.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_0
  - sqlalchemy=1.4.26=py37h5e8e339_0
  - sqlite=3.36.0=h9cd32fc_2
  - stone=3.2.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.2=pyhd8ed1ab_0
  - toposort=1.7=pyhd8ed1ab_0
  - tornado=6.1=py37h5e8e339_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.4.3=py37h5e8e339_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - wrapt=1.13.3=py37h5e8e339_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.7.0=py37h5e8e339_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - asdf-standard==1.0.1
    - asdf-transform-schemas==0.2.2
    - cloudpickle==1.6.0
    - colorama==0.4.3
    - commonmark==0.9.1
    - pyscf==1.7.5
    - qc-iodata
    - rich==7.1.0
    - ruamel-yaml
    - ruamel-yaml-clib==0.2.6
    - scalene==1.1.2
    - scipy==1.4.1
    - semantic-version==2.10.0
    - yamlable
    - yamlfmt
