---
channels:
  - psi4
  - conda-forge
  - defaults
dependencies:
  - cython  # only needed for pyquante2
  - h5py=3.1
  - openbabel
  - pip
  - psi4
  - pytest-cov
  - pytest-shutil
  - python=3.9
  - pip:
      - pyscf
      - qc-iodata
